#!/usr/bin/env bash
FAILURES=0

apply() {
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ] || echo 'Error' $((++FAILURES))
}
check() {
    "$@" || echo 'Error' $((++FAILURES))
}
uncheck() {
    ! "$@" || echo 'Error' $((++FAILURES))
}

# uncheck which brew
#  - CI nodes have brew installed)
#  - Removing brew before tests is not an option: ruby is provided through brew
echo 'Apply init.pp...'
apply tests/init.pp
check which brew

exit $FAILURES
