#!/usr/bin/env bash
FAILURES=0

apply() {
    puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ]
    FAILURES=$((FAILURES + $?))
}
check() {
    "$@"
    FAILURES=$((FAILURES + $?))
}

echo 'Apply init.pp...'
apply tests/init.pp
check which brew

if [ "$FAILURES" -ne "0" ]; then
    exit 1
fi
