#!/usr/bin/env bash
FAILURES=0

apply_error() {
    # expecting an error and a change, so code 6
    echo "apply_error" $@
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 6 ] || echo 'Error' $((++FAILURES))
}
apply() {
    echo "apply" $@
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ] || echo 'Error' $((++FAILURES))
}
check() {
    echo "check" $@
    "$@" || echo 'Error' $((++FAILURES))
}
uncheck() {
    echo "uncheck" $@
    ! "$@" || echo 'Error' $((++FAILURES))
}

# test default install (used to be formula-only)
uncheck which ack
check which nano # nano is installed on CI by default
uncheck which rar
uncheck stat /Applications/Nano.app
apply tests/install_brew.pp
check which ack  # installed from formula
check which rar  # installed from cask (not expected by provider but not a problem)
check which nano # installed from formula over cask
check brew list nano
uncheck stat /Applications/Nano.app # not installed, shadowed by formula

apply tests/uninstall.pp
uncheck which ack
uncheck which rar
check which nano # nano is installed on CI by default
uncheck brew list nano
uncheck stat /Applications/Nano.app

# test universal install (provider will try formula and cask)
apply tests/install_homebrew.pp
check which ack  # installed from formula
check which rar  # installed from cask (not expected by provider but not a problem)
check which nano  # installed from formula over cask
check brew list nano
uncheck stat /Applications/Nano.app  # not installed, shadowed by formula

apply tests/uninstall.pp
uncheck which ack
uncheck which rar
check which nano # nano is installed on CI by default
uncheck brew list nano
uncheck stat /Applications/Nano.app

# test cask-only install
apply_error tests/install_brewcask.pp
uncheck which ack  # not installed: only formula available
check which rar  # installed from cask explicitly
check which nano # nano is installed on CI by default
check brew list nano # it's actually the other nano!
check stat /Applications/Nano.app # installed from cask

apply tests/uninstall.pp
uncheck which ack
uncheck which rar
check which nano # nano is installed on CI by default
uncheck brew list nano
uncheck stat /Applications/Nano.app

exit $FAILURES
