#!/usr/bin/env bash
FAILURES=0

apply() {
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ] || echo 'Error' $((++FAILURES))
}
check() {
    "$@" || echo 'Error' $((++FAILURES))
}
uncheck() {
    ! "$@" || echo 'Error' $((++FAILURES))
}

uncheck brew tap | grep homebrew/ffmpeg
uncheck which ffmpeg
echo 'Apply tap_and_install.pp...'
apply tests/tap_and_install.pp
check brew tap | grep homebrew/ffmpeg
check which ffmpeg
uncheck ffmpeg -V 2>&1 | tr ' ' '\n' | grep srt
echo 'Apply untap.pp...'
apply tests/untap.pp
uncheck brew tap | grep homebrew/ffmpeg
uncheck which ffmpeg

echo 'Apply tap_and_install_options.pp...'
apply tests/tap_and_install_options.pp
check brew tap | grep homebrew/ffmpeg
check which ffmpeg
check ffmpeg -V 2>&1 | tr ' ' '\n' | grep srt
echo 'Apply untap.pp...'
apply tests/untap.pp
uncheck brew tap | grep homebrew/ffmpeg
uncheck which ffmpeg

exit $FAILURES
