#!/usr/bin/env bash
FAILURES=0

apply_error() {
    # expecting an error and a change, so code 6
    echo "apply_error" $@
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 6 ] || echo 'Error' $((++FAILURES))
}
apply() {
    echo "apply" $@
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ] || echo 'Error' $((++FAILURES))
}
check() {
    echo "check" $@
    "$@" || echo 'Error' $((++FAILURES))
}
uncheck() {
    echo "uncheck" $@
    ! "$@" || echo 'Error' $((++FAILURES))
}

uncheck brew tap | grep denji/nginx
uncheck which nginx
apply_error tests/tap_and_install.pp
check brew tap | grep denji/nginx
check which nginx
uncheck nginx -V 2>&1 | tr ' ' '\n' | grep redis2
apply tests/untap.pp
uncheck brew tap | grep denji/nginx
uncheck which nginx

apply_error tests/tap_and_install_options.pp
check brew tap | grep denji/nginx
check which nginx
check nginx -V 2>&1 | tr ' ' '\n' | grep redis2
apply tests/untap.pp
uncheck brew tap | grep denji/nginx
uncheck which nginx

exit $FAILURES
