#!/usr/bin/env bash
FAILURES=0

apply_error() {
    # expecting an error and a change, so code 6
    echo "apply_error" $@
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 6 ] || echo 'Error' $((++FAILURES))
}
apply() {
    echo "apply" $@
    sudo puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ] || echo 'Error' $((++FAILURES))
}
check() {
    echo "check" $@
    "$@" || echo 'Error' $((++FAILURES))
}
uncheck() {
    echo "uncheck" $@
    ! "$@" || echo 'Error' $((++FAILURES))
}

# uncheck which brew
#  - CI nodes have brew installed)
#  - Removing brew before tests is not an option: ruby is provided through brew
apply tests/init.pp
check which brew

exit $FAILURES
