#!/usr/bin/env bash
FAILURES=0

apply() {
    sudo BUNDLE_GEMFILE="$GEMFILE" FUTURE_PARSER="$FUTURE_PARSER" bundle exec \
        puppet apply --detailed-exitcodes --debug "$@" || [ $? -eq 2 ]
    FAILURES=$((FAILURES + $?))
}
check() {
    "$@"
    FAILURES=$((FAILURES + $?))
}

if [ "${CIRCLE_NODE_INDEX}" = "0" ]; then
    echo 'Apply init.pp...'
    apply examples/init.pp
    check which brew
elif [ "${CIRCLE_NODE_INDEX}" = "1" ]; then
    echo 'Test apply token.pp...'
    apply examples/token.pp
    check cat /etc/environment | grep HOMEBREW_GITHUB_API_TOKEN
else
    echo 'Apply install_options.pp...'
    apply examples/install_options.pp
    check which ack

    echo 'Apply packages.pp...'
    apply examples/packages.pp
    check stat /Applications/clementine.app/Contents/MacOS/clementine
    check which git
    check stat "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    check which bzr

    echo 'Apply tap.pp...'
    apply examples/tap.pp
    check which gc2qif

    echo 'Apply tap_priority.pp...'
    apply examples/tap_priority.pp
    check brew list ncl
fi

if [ "$FAILURES" -ne "0" ]; then
    exit 1
fi
