#!/usr/bin/env bash

pre-commit run --all-files &&
ruby --version &&
pdk --version &&
puppet --version &&
pdk validate &&
bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop &&
bundle exec rake parallel_spec
