#!/usr/bin/env zsh

eval "$(rbenv init - zsh)"

pdk_version=1.7.1
ruby_version=${1:-2.7.8}
puppet_version=${2:-6}

rbenv install --skip-existing "$ruby_version" &&
rbenv shell "$ruby_version" &&
gem install "pdk:$pdk_version" --conservative &&
rm -f Gemfile.lock &&
pdk validate --puppet-version "$puppet_version" ||
pdk validate --puppet-version "$puppet_version"
