#!/usr/bin/env bash

source tests/util.bash

echo 'Test apply token.pp...'
apply tests/token.pp
check cat /etc/environment | grep HOMEBREW_GITHUB_API_TOKEN

if [ "$FAILURES" -ne "0" ]; then
    exit 1
fi
