#!/usr/bin/env bash

source tests/util.bash

apply tests/install_options.pp
check which ack

apply tests/packages.pp
check stat /Applications/clementine.app/Contents/MacOS/clementine
check which git
check stat "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
check which bzr

apply tests/tap.pp
check which gc2qif

apply tests/tap_priority.pp
check which f2c

exit $FAILURES
