version: 2.1

orbs:
  linter: talkiq/linter@4.0.0
  macos: circleci/macos@2

jobs:
  test:
    macos:
      xcode: << parameters.xcode_version >>
    resource_class: macos.x86.medium.gen2
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      STRICT_VARIABLES: "yes"
    parameters:
      xcode_version:
        type: string
      puppet_version:
        type: string
      ruby_version:
        type: string
      pdk_version:
        type: string
      lint_version:
        type: string
      other_gems:
        type: string
      test_name:
        type: string
    steps:
      - checkout
      - macos/switch-ruby:
          version: << parameters.ruby_version >>
      - run: >-
          gem install -N
          << parameters.other_gems >>
          "puppet:<< parameters.puppet_version >>"
          "pdk:<< parameters.pdk_version >>"
          "puppet-lint:<< parameters.lint_version >>"
      - run: puppet-lint manifests/init.pp
      - run: puppet-lint manifests/install.pp
      - run: puppet-lint manifests/compiler.pp
      - run: puppet parser validate --noop manifests/init.pp
      - run: puppet parser validate --noop manifests/install.pp
      - run: puppet parser validate --noop manifests/compiler.pp
      - run: pdk build
      - run: puppet module install pkg/thekevjames-homebrew-*.tar.gz
      - run: ./tests/<< parameters.test_name >>
      - store_artifacts:
          path: pkg/

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          pre-steps:
            - run: apt-get update
            - run: apt-get install -qy shellcheck
      # - test:
      #     name: <<matrix.test_name>>-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
      #     matrix:
      #       parameters:
      #         xcode_version:
      #           - 12.5.1
      #         other_gems:
      #           - '"bundler:~>2.3.0" "public_suffix:~>4"'
      #         puppet_version:
      #           - '~>4'
      #           - '~>5'
      #         ruby_version:
      #           - '2.5'
      #         pdk_version:
      #           - '~>2'
      #         lint_version:
      #           - '~>2'
      #         test_name:
      #           - test1
      #           # - test2
      #           # - test3
      # - test:
      #     name: ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>-<<matrix.test_name>>
      #     matrix:
      #       parameters:
      #         xcode_version:
      #           - 12.5.1
      #         other_gems:
      #           - '"bundler:~>2.3.0" "public_suffix:~>4" "semantic_puppet:~>1.0.0"'
      #         puppet_version:
      #           - '~>6'
      #           - '~>7'
      #         ruby_version:
      #           - '2.5'
      #         pdk_version:
      #           - '~>2'
      #         lint_version:
      #           - '~>2'
      #         test_name:
      #           - test1
      #           # - test2
      #           # - test3
      # - test:
      #     name: ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>-<<matrix.test_name>>
      #     matrix:
      #       parameters:
      #         xcode_version:
      #           - 13.4.1
      #         other_gems:
      #           - '"bundler:~>2.4.0"'
      #         puppet_version:
      #           - '~>4'
      #           - '~>5'
      #         ruby_version:
      #           - '2.6'
      #         pdk_version:
      #           - '~>2'
      #         lint_version:
      #           - '~>2'
      #         test_name:
      #           - test1
      #           # - test2
      #           # - test3
      # - test:
      #     name: ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>-<<matrix.test_name>>
      #     matrix:
      #       parameters:
      #         xcode_version:
      #           - 13.4.1
      #         other_gems:
      #           - '"bundler:~>2.4.0" "semantic_puppet:~>1.0.0"'
      #         puppet_version:
      #           - '~>6'
      #           - '~>7'
      #         ruby_version:
      #           - '2.6'
      #         pdk_version:
      #           - '~>2'
      #         lint_version:
      #           - '~>2'
      #         test_name:
      #           - test1
      #           # - test2
      #           # - test3
      - test:
          name: ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>-<<matrix.test_name>>
          matrix:
            parameters:
              xcode_version:
                - 14.3.1
              other_gems:
                - ''
              puppet_version:
                # -'~5' sync library dropped in ruby 2.7
                - '~>6'
                - '~>7'
              ruby_version:
                - '2.7'
              pdk_version:
                - '~>3'
              lint_version:
                - '~>4'
              test_name:
                - test1
                - test2
                - test3
      # - test:
      #     name: ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>-<<matrix.test_name>>
      #     matrix:
      #       parameters:
      #         xcode_version:
      #           - 15.3.0
      #         other_gems:
      #           - ''
      #         puppet_version:
      #           # - '~>6' URI.escape() droppd in 3.0,
      #           - '~>7'
      #         ruby_version:
      #           - '3.0'
      #         pdk_version:
      #           - '~>3'
      #         lint_version:
      #           - '~>4'
      #         test_name:
      #           - test1
      #           # - test2
      #           # - test3
      # - test:
      #     name: ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>-<<matrix.test_name>>
      #     matrix:
      #       parameters:
      #         xcode_version:
      #           - 15.3.0
      #         other_gems:
      #           - ''
      #         puppet_version:
      #           # - '~>6' URI.escape() droppd in 3.0, .untaint() dropped in 3.2
      #           - '~>7'
      #           - '~>8'
      #         ruby_version:
      #           - '3.1'
      #           - '3.2'
      #           - '3.3'
      #         pdk_version:
      #           - '~>3'
      #         lint_version:
      #           - '~>4'
      #         test_name:
      #           - test1
      #           # - test2
      #           # - test3
