version: 2.1

orbs:
  linter: talkiq/linter@4.0.0

jobs:
  test:
    docker:
      - image: ruby:<< parameters.ruby_version >>
    resource_class: small
    environment:
      STRICT_VARIABLES: "yes"
    parameters:
      pdk:
        type: boolean
      puppet_version:
        type: string
      ruby_version:
        type: string
    steps:
      - checkout
      - run: gem install -N puppet-lint "puppet:<< parameters.puppet_version >>"
      - when:
          condition: << parameters.pdk >>
          steps:
            - run: gem install -N pdk
      - run: puppet-lint manifests/init.pp
      - run: puppet-lint manifests/install.pp
      - run: puppet-lint manifests/compiler.pp
      - run: puppet parser validate --noop manifests/init.pp
      - run: puppet parser validate --noop manifests/install.pp
      - run: puppet parser validate --noop manifests/compiler.pp
      - when:
          condition: << parameters.pdk >>
          steps:
            - run: pdk build
      - unless:
          condition: << parameters.pdk >>
          steps:
            - run: puppet module build
      - run: puppet module install pkg/thekevjames-homebrew-*.tar.gz
      # - run: ./test
      - store_artifacts:
          path: pkg/

  rake:
    docker:
      - image: ruby:<< parameters.ruby_version >>
    resource_class: small
    environment:
      PUPPET_GEM_VERSION: << parameters.puppet_version >>
    parameters:
      ruby_version:
        type: string
      puppet_version:
        type: string
      check:
        type: string
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake << parameters.check >>

  validate:
    docker:
      - image: ruby:<< parameters.ruby_version >>
    resource_class: small
    parameters:
      ruby_version:
        type: string
      puppet_version:
        type: string
      pdk_version:
        type: string
    steps:
      - checkout
      - run: gem install pdk:<< parameters.pdk_version>>
      - run: pdk validate --puppet-version=<< parameters.puppet_version >> || true
      - run: pdk validate --puppet-version=<< parameters.puppet_version >>

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          pre-steps:
            - run: apt-get update
            - run: apt-get install -qy shellcheck

      - validate:
          ruby_version: 2.7.8
          puppet_version: 6.29.0
          pdk_version: 1.18.1

      - rake:
          name: syntax
          ruby_version: 2.7.8
          puppet_version: 6.29.0
          check: syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
      - rake:
          name: unit-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
          check: parallel_spec
          matrix:
            parameters:
              ruby_version:
                - 2.6.0
                - 2.6.10
                - 2.7.0
                - 2.7.8
              puppet_version:
                - ~>6.0
      - rake:
          name: unit-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
          check: parallel_spec
          matrix:
            parameters:
              ruby_version:
                - 2.5.0
                - 2.5.9
              puppet_version:
                - ~>6.0.0
                - ~>6.0
      - rake:
          name: unit-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
          check: parallel_spec
          matrix:
            parameters:
              ruby_version:
                - 2.4.0
                - 2.4.10
              puppet_version:
                - ~>4.0.0
                - ~>4.0
                - ~>5.0.0
                - ~>5.0
                - ~>6.0.0
                - ~>6.0
            exclude:
              - ruby_version: 2.4.10
                puppet_version: ~>4.0.0
