version: 2.1

orbs:
  linter: talkiq/linter@4.0.0
  macos: circleci/macos@2

jobs:
  test:
    macos:
      xcode: 15.2.0
    resource_class: macos.x86.medium.gen2
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      STRICT_VARIABLES: "yes"
    parameters:
      puppet_version:
        type: string
      ruby_version:
        type: string
      pdk_version:
        type: string
      other_gems:
        type: string
      test_script:
        type: string
    steps:
      - checkout
      - macos/switch-ruby:
          version: << parameters.ruby_version >>
      - run: gem install -N << parameters.other_gems >> "puppet:<< parameters.puppet_version >>"
      - when:
          condition: << parameters.pdk_version >>
          steps:
            - run: gem install -N "pdk:<< parameters.pdk_version >>"
      - run: puppet-lint manifests/init.pp
      - run: puppet-lint manifests/install.pp
      - run: puppet-lint manifests/compiler.pp
      - run: puppet parser validate --noop manifests/init.pp
      - run: puppet parser validate --noop manifests/install.pp
      - run: puppet parser validate --noop manifests/compiler.pp
      - when:
          condition: << parameters.pdk_version >>
          steps:
            - run: pdk build
      - unless:
          condition: << parameters.pdk_version >>
          steps:
            - run: puppet module build
      - run: sudo puppet module install pkg/thekevjames-homebrew-*.tar.gz
      - run: ./<< parameters.test_script >>
      - store_artifacts:
          path: pkg/

workflows:
  run-jobs:
    jobs:
      # - linter/pre-commit:
      #     pre-steps:
      #       - run: apt-get update
      #       - run: apt-get install -qy shellcheck

      # - test:
      #     name: test-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
      #     matrix:
      #       parameters:
      #         other_gems: ['"bundler:<2.4" "thor:<1.3" "semantic_puppet:<1.1" "puppet-lint:<3" "facter:<4.6" "public_suffix:<5"']
      #         puppet_version:
      #           - '<5.0.0'
      #           - '<6.0.0'
      #         ruby_version:
      #           - '2.5.9'
      #           - '2.6.10'
      #         pdk_version:
      #           - '<3'
      # - test:
      #     name: test-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
      #     matrix:
      #       parameters:
      #         other_gems: ['"bundler:<2.4" "thor:<1.3" "semantic_puppet:<1.1" "puppet-lint:<3" "facter:<4.6" "public_suffix:<5"']
      #         puppet_version:
      #           - '<7.0.0'
      #           - '<8.0.0'
      #         ruby_version:
      #           - '2.5.9'
      #         pdk_version:
      #           - '<3'
      # - test:
      #     name: test-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
      #     matrix:
      #       parameters:
      #         other_gems: ['"bundler:<2.5" "semantic_puppet:<1.1" "puppet-lint:<3"']
      #         puppet_version:
      #           - '<7.0.0'
      #           - '<8.0.0'
      #         ruby_version:
      #           - '2.6.10'
      #         pdk_version:
      #           - '<3'
      # - test:
      #     name: test-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
      #     matrix:
      #       parameters:
      #         other_gems: ['"puppet-lint"']
      #         puppet_version:
      #           - '<7.0.0'
      #           - '<8.0.0'
      #         ruby_version:
      #           - '2.7.8'
      #         pdk_version:
      #           - '>0'
      - test:
          name: ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>-<<matrix.test_script>>
          matrix:
            parameters:
              other_gems: ['"puppet-lint"']
              puppet_version:
                - '<8.0.0'
                # - '<9.0.0'
              ruby_version:
                - '2.7'
                # - '3.0'
                # - '3.1'
                - '3.2'
              pdk_version:
                - '>0'
              test_script:
                - test1
                - test2
                - test3
