version: 2.1

orbs:
  linter: talkiq/linter@4.0.0

jobs:
  test:
    docker:
      - image: ruby:<< parameters.ruby_version >>
    environment:
      STRICT_VARIABLES: "yes"
    parameters:
      pdk:
        type: boolean
      puppet_version:
        type: string
      ruby_version:
        type: string
    steps:
      - checkout
      - run: gem install -N puppet-lint "puppet:<< parameters.puppet_version >>"
      - when:
          condition: << parameters.pdk >>
          steps:
            - run: gem install -N pdk
      - run: puppet-lint manifests/init.pp
      - run: puppet-lint manifests/install.pp
      - run: puppet-lint manifests/compiler.pp
      - run: puppet parser validate --noop manifests/init.pp
      - run: puppet parser validate --noop manifests/install.pp
      - run: puppet parser validate --noop manifests/compiler.pp
      - when:
          condition: << parameters.pdk >>
          steps:
            - run: pdk build
      - unless:
          condition: << parameters.pdk >>
          steps:
            - run: puppet module build
      - run: puppet module install pkg/thekevjames-homebrew-*.tar.gz
      # - run: ./test
      - store_artifacts:
          path: pkg/

  rake:
    docker:
      - image: ruby:<< parameters.ruby_version >>
    environment:
      PUPPET_GEM_VERSION: << parameters.puppet_version >>
    parameters:
      puppet_version:
        type: string
      ruby_version:
        type: string
      check:
        type: string
    steps:
      - checkout
      - run: bundle -v
      - run: gem --version
      - run: bundle install
      - run: bundle exec rake << parameters.check >>

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          pre-steps:
            - run: apt-get update
            - run: apt-get install -qy shellcheck

      - test:
          name: test-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
          pdk: false
          matrix:
            parameters:
              puppet_version:
                - '<5.0.0'
                - '<6.0.0'
              ruby_version:
                - '2.2.10'
                - '2.3.8'
                - '2.4.10'
                - '2.5.9'
                - '2.6.7'
      - test:
          name: test-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
          pdk: true
          matrix:
            parameters:
              puppet_version:
                - '<7.0.0'
              ruby_version:
                - '2.5.9'
                - '2.6.7'
                - '2.7.3'

      - rake:
          name: syntax
          ruby_version: 2.4.4
          puppet_version: ~>5.5
          check: syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
      - rake:
          name: unit-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
          check: parallel_spec
          matrix:
            parameters:
              ruby_version:
                - '2.6.0'
                - '2.6.10'
                - '2.7.0'
                - '2.7.8'
              puppet_version:
                - '~>5.0'
                - '~>6.0.0'
                - '~>6.0'
      - rake:
          name: unit-ruby<<matrix.ruby_version>>-pup<<matrix.puppet_version>>
          check: parallel_spec
          matrix:
            parameters:
              ruby_version:
                - '2.3.8'
                - '2.4.0'
                - '2.4.10'
                - '2.5.0'
                - '2.5.9'
              puppet_version:
                - '~>4.0.0'
                - '~>4.0'
                - '~>5.0.0'
                - '~>5.0'
                - '~>6.0.0'
                - '~>6.0'
            exclude:
              - ruby_version: '2.4.10'
                puppet_version: '~>4.0.0'
